name = "aether"
name_pretty = "Aether Menu"
global_search = false
keywords = [ "aether", "menu" ]
fixed_order = true
history = false
history_when_empty = false


[[entries]]
text = "Audio"
action = "kitty --class wiremix wiremix"
keywords = [ "audio", "wiremix" ]

[[entries]]
text = "Bluetooth"
action = "kitty --class bluetui bluetui"
keywords = [ "bluetooth", "bluetui" ]

[[entries]]
text = "Wifi"
action = "kitty --class impala impala"
keywords = [ "network", "wifi", "wi-fi", "wireless", "impala" ]
