name = "aether"
name_pretty = "Aether Menu"
global_search = false
keywords = [ "aether", "menu" ]
fixed_order = true
history = false
history_when_empty = false


[[entries]]
text = "Audio"
action = "kitty --class wiremix wiremix"
keywords = [ "audio", "wiremix" ]

[[entries]]
text = "Bluetooth"
action = "kitty --class bluetui bluetui"
keywords = [ "bluetooth", "bluetui" ]

[[entries]]
text = "Idle"
async = """echo "Idle inhibiton: $(sh /etc/aether/power/scripts/inhibition-status.sh)" """
action = "sh /etc/aether/power/scripts/inhibition-toggle.sh"
keywords = [ "idle", "inhibition" ]

[[entries]]
text = "Power"
submenu = "power"
keywords = [ "power", "reboot", "restart", "sleep", "suspend", "hibernate", "sleep", "logout", "shutdown" ]

[[entries]]
text = "Screenshot"
submenu = "screenshot"
keywords = [ "screenshot", "capture" ]

[[entries]]
text = "Wifi"
action = "kitty --class impala impala"
keywords = [ "network", "wifi", "wi-fi", "wireless", "impala" ]
