name = "power"
name_pretty = "Power"
global_search = false
keywords = [ "power" ]
fixed_order = true
history = false
history_when_empty = false

[[entries]]
text = "Shutdown"
action = "systemctl poweroff"
icon = "system-shutdown-symbolic"
keywords = [ "shutdown", "power", "poweroff", "off" ]

[[entries]]
text = "Reboot"
action = "systemctl reboot"
icon = "system-reboot-symbolic"
keywords = [ "reboot", "restart" ]

[[entries]]
text = "Suspend"
action = "systemctl suspend"
icon = "system-suspend-symbolic"
keywords = [ "suspend", "sleep" ]

[[entries]]
text = "Hibernate"
action = "systemctl hibernate"
icon = "system-hibernate-symbolic"

[[entries]]
text = "Logout"
action = "hyprctl dispatch exit"
icon = "system-log-out-symbolic"

[[entries]]
text = "Lock Screen"
action = "loginctl lock-session"
icon = "system-lock-screen-symbolic"

