name = "screenshot"
name_pretty = "Screenshot"
global_search = false
keywords = [ "aether", "menu" ]
fixed_order = true
history = false
history_when_empty = false

[[entries]]
text = "Region"
action = "sh /etc/aether/screen-capture/scripts/screenshot.sh region"

[[entries]]
text = "Window"
action = "sh /etc/aether/screen-capture/scripts/screenshot.sh window"

[[entries]]
text = "Monitor"
action = "sh /etc/aether/screen-capture/scripts/screenshot.sh output"

